### ISSUE TITLE
[BUG] Exports for config object does not work in version 14.0.6 but works in 14.0.5

### ISSUE THREAD

**Issue by darekg11** [seppevs/migrate-mongo#474]
## Bug Description
Export of `config` seems to be broken in version 14.0.6 which introduced support for `Full ESM support with native import/export`

## Environment
- **migrate-mongo version**: 14.0.6
- **Node.js version**: 25.2.1
- **MongoDB version**: 8
- **Operating System**: Ubuntu

## Steps to Reproduce
1. Init new Node project
2. Install `migrate-mongo` dependency in version `14.0.6`
3. Try to run following code:
```
const { config: MongoMigrateConfig, up: MongoMigrateUp, database: MongoMigrateDatabase } = require("migrate-mongo");
MongoMigrateConfig.set({});
```

## Expected Behavior
Should work without throwing any errors

## Actual Behavior
This returns error that `set is not a function` because `MongoMigrateConfig` is null

## Additional Context
Reverting back to version `14.0.5` makes everything work again without changing anything in the code.

Could you please tell me if this is a bug or if config should be now required differently? According to docs this should still work as expected:
https://github.com/seppevs/migrate-mongo/tree/master?tab=readme-ov-file#configsetyourconfigobject

**Comment by frederik-b** [comment]
I can reproduce this and might have relevant additonal info:

Version 14.0.5
```
import migrate from 'migrate-mongo'
console.log(migrate)
==> {
  init: [AsyncFunction (anonymous)],
  create: [AsyncFunction (anonymous)],
  up: [AsyncFunction (anonymous)],
  down: [AsyncFunction (anonymous)],
  status: [AsyncFunction (anonymous)],
  database: { connect: [AsyncFunction: connect] },
  config: {
    DEFAULT_CONFIG_FILE_NAME: 'migrate-mongo-config.js',
    set: [Function: set],
    shouldExist: [AsyncFunction: shouldExist],
    shouldNotExist: [AsyncFunction: shouldNotExist],
    getConfigFilename: [Function: getConfigFilename],
    read: [AsyncFunction: read]
  }
}
```

Version 14.0.6/7
```
import migrate from 'migrate-mongo'
console.log(migrate)
==> Promise { <pending> }
```


I think in my ts setup this get's rewritten to require calls...
so this might be a commonjs/esmodule issue
